name: MCWarfare
main: com.orange451.mcwarfare.KitPvP
version: 1.0
website: http://orangegaming.webatu.com/
author: orange451
softdepend: [TagAPI]
commands: 
  war:
    description:
    usage:
  givexp:
    description:
    usage:
  givegun:
    description:
    usage:
  setkills:
    description:
    usage:
  setdeaths:
    description:
    usage:
  opex:
    description:
    usage:
  mod:
    description:
    usage:
  kick:
    description:
    usage:
  ban:
    description:
    usage:
  unban:
    description:
    usage:
  banip:
    description:
    usage:
  eban:
    description:
    usage:
  ban-ip:
    description:
    usage:
  giveperk:
    description:
    usage:
  tag:
    description:
    usage:
  profile:
    description:
    usage:
  dprofile:
    description:
    usage:
  codclient:
    description:
    usage: